language: python

python:
  - '3.5'

install: pip install -r requirements.txt

install: pip install -r requirements.txt

script:
  - pelican content --fatal=warnings

after_failure:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then make revert_push; fi'

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then make github; fi' 

branches:
  only:
  - master

env:
  global:
    - secure: "xuNIN7LAenb/NvNKMIas9JQYgHvGEUy0i4twjqJ5ibO5o5yorbAwjFYiMQ+Sc9ydpDUS05+DU7JdalZlDnpwNULrAKmbFsBcDEX99NsJC++NC9f21BxBkX5m5uflU3Ka1Fky9fIgBZ50gCwB4N2hQnzUdro4tZnGyjh8EpF6gK++4FvYULwHmKszag8fqNMDl8lBw+UefdONyUvLc92AO63QHYFkDaovS8R2N8kH5DMeEBzh+Po9iJSXuRSWHraYln5i0CSEAeNpwWZfiHLxnq1sKn3trI70PYSJ+RnDBoJqZvYjzySgg6991eejEnm5d66nXw0EJLMPD8ncqZlHNFfgWGOysvY67CtDhtKE0LP1ZnJocD9W1kJrDaZb5/ERgY7DPW6JBPyCjj1REj0pF950dJeDua/TT7GPfHtyKM/oOd8cFm2IJKeK35iwJxxiNHTYyGSZLYpKMBmTP0LIIsXcGzUBPZ9mSPSy+nd3FA0kvNPJTDj4XdG0BlwiqvYZEA8Suy/WMXb1eiAVQv0WNmM3lvkwxP0SzJYN5GsZ8YIFqdqGbh5nWeUZlUr0cFVFNheILmU2ud1jBrX59KebAWKJeQUrw1JL3ahtP4PeRH3HUZaixMnYU+31oH7aSRBrIo9kyUtR65EwawKiYqoKmHV3e6DQMEItG1Bhlk6+bhE="

notifications:
    webhooks: https://www.travisbuddy.com/

###
### Configuration exemple pour la production
###
spring.cloud.config.override-system-properties: false

spring.messages.basename: i18n/messages
spring.rabbitmq.host: rabbitmq-i.csn.cnaf ## A configurer
spring.rabbitmq.port: 5673 ## A configurer
spring.rabbitmq.username: rabbitmqi1 ## A configurer
spring.rabbitmq.password: rabbitmqi1 ## A configurer

spring.datasource.type: com.zaxxer.hikari.HikariDataSource
spring.datasource.url: jdbc:postgresql://dbpha-actif-i.db.si.cnaf.info:50000/pha000i ## A configurer exemple jdbc:postgresql://localhost:5432/HabilitationsPartenairesMiddle
spring.datasource.name:
spring.datasource.username: umpha000 ## A configurer
spring.datasource.password: 2OHGNu2w ## A configurer
spring.datasource.hikari.maximum-pool-size: 5 ## A configurer

spring.jpa.open-in-view: false
spring.jpa.hibernate.ddl-auto: none
spring.jpa.hibernate.naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
spring.jpa.hibernate.naming.implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
spring.jpa.database-platform: fr.cnaf.middle.partenaire.habilitation.domain.util.FixedPostgreSQL82Dialect
spring.jpa.database: POSTGRESQL
spring.jpa.show-sql: false

spring.jpa.properties.hibernate.cache.use_second_level_cache: true
spring.jpa.properties.hibernate.cache.use_query_cache: false
spring.jpa.properties.hibernate.generate_statistics: false
spring.jpa.properties.hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
spring.jpa.properties.hibernate.cache.hazelcast.instance_name: habilitationspartenairesmiddle
spring.jpa.properties.hibernate.cache.use_minimal_puts: true
spring.jpa.properties.hibernate.cache.hazelcast.use_lite_member: true
spring.jpa.properties.hibernate.default_schema: pbp000 ## A configurer

liquibase.contexts: prod
liquibase.default-schema: pbp000 ## A configurer

# ===================================================================
# JHipster specific properties
# ===================================================================

# Hibernate 2nd level cache, used by CacheConfiguration
jhipster.cache.hazelcast.timeToLiveSeconds: 3600
jhipster.cache.hazelcast.backupCount: 1

cnaf.habilitationspartenairesmiddle.propagationErrorFilePath: PropagationError.log ## A configurer chemin vers le fichier d'erreur de propagation
cnaf.habilitationspartenairesmiddle.importErrorFilePath: /tmp/importError/errors.csv ## A configurer chemin vers le fichier d'erreur d'import LOH
cnaf.habilitationspartenairesmiddle.habilitation.lohQueueName: cnaf.partenaires.pha.consumerBP
cnaf.habilitationspartenairesmiddle.habilitation.lohErrorsQueueName: cnaf.partenaires.pha.consumerErrorsBP
cnaf.habilitationspartenairesmiddle.habilitation.lohErrorsExchangeName : cnaf.partenaires.pha.consumerErrorsBPExchange
cnaf.habilitationspartenairesmiddle.rabbitmq.enable : false
cnaf.habilitationspartenairesmiddle.isu.security.uri: http://securite-portail-qualif.intra.cnaf:9081 ## A configurer url appel ISU exemple http://securite-portail-qualif.intra.cnaf:9081
cnaf.habilitationspartenairesmiddle.isu.security.portalName: partenaires-i.caf.fr ## A configurer nom portail exemple partenaires-f.caf.fr

cnaf.habilitationspartenairesmiddle.isu.oauth.uri: http://securite-auth-qualif.intra.cnaf:9999 ## A configurer url recuperation de token ISU exemple http://securite-auth-qualif.intra.cnaf:9999
cnaf.habilitationspartenairesmiddle.isu.oauth.clientId: FL4tmmv2U+vQIHSrCgXcgQ==
cnaf.habilitationspartenairesmiddle.isu.oauth.clientSecret: XpshMViDAhYLv2t+LoyZEioc0xahz698sc4RfLvNizc=
cnaf.habilitationspartenairesmiddle.isu.oauth.scope: partenaires
cnaf.habilitationspartenairesmiddle.isu.oauth.subjectValue: 123

cnaf.habilitationspartenairesmiddle.liferay.host: http://vlivajee01-partenaires-portail-tc8-i1.app.si.test-cnaf.info ## A configurer exemple http://localhost
cnaf.habilitationspartenairesmiddle.liferay.port: 8080 ## A configurer
cnaf.habilitationspartenairesmiddle.liferay.technicalUser.username: PHATechnical ## A configurer
cnaf.habilitationspartenairesmiddle.liferay.technicalUser.password: L!ferayPha ## A configurer
cnaf.habilitationspartenairesmiddle.liferay.web.id: liferay.com
